#!/usr/bin/env bash
# advanced task
echo "$$" > /var/run/myscript.pid
trap 'echo "I hate the kill command"' 15
trap 'echo "Y U no love me?!"' 2
trap 'rm -f /var/run/myscript.pid; exit"' 3
while true
do
	echo "To infinity and beyond"
done
