#!/usr/bin/env bash
# all process
if [ $# -eq 0 ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
fi
if [[ $1 == "start" ]]
then
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [[ $1 == "stop" ]]
then
	pkill -f ./manage_my_process
	if [ -e /var/run/my_process.pid ]
	then
		rm -f /var/run/my_process.pid
	fi
	echo "manage_my_process stopped"
elif [[ $1 == "restart" ]]
then
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process restarted"
fi
